export const blogs = [
    {
        id: 1,
        category: "Design",
        title:  "UX review presentations",
        short: "How do you create compelling presentations that wow your colleagues and impress your managers?",
        author_id: 1,
        author_name: "Olivia Rhye",
        createdAt: '2025-01-20',
        preview: "/blogs/blog1/ImgBlog1.png",
        avatar: "blogs/blog1/AvatarBlog1.png",

    },
    {
        id: 2,
        category: "Product",
        title:  "Migrating to Linear 101",
        short: "Linear helps streamline software projects, sprints, tasks, and bug Letter spacing. Here’s how to get started.",
        author_id: 2,
        author_name: "Phoenix Baker",
        createdAt: '2025-01-19',
        preview: "/blogs/blog2/ImgBlog2.png",
        avatar: "blogs/blog2/AvatarBlog2.png",

    },
    {
        id: 3,
        category: "Software Engineering",
        title:  "Building your API Stack",
        short: "The rise of RESTful APIs has been met by a rise in tools for creating, testing, and managing them.",
        author_id: 3,
        author_name: "Lana Steiner",
        createdAt: '2025-01-18',
        preview: "/blogs/blog3/ImgBlog3.png",
        avatar: "blogs/blog3/AvatarBlog3.png",

    },
    {
        id: 4,
        category: "Management",
        title:  "Bill Walsh leadership lessons",
        short: "Like to know the secrets of transforming a 2-14 team into a 3x Super Bowl winning Dynasty?",
        author_id: 4,
        author_name: "Alec Whitten",
        createdAt: '2025-01-17',
        preview: "/blogs/blog4/ImgBlog4.png",
        avatar: "blogs/blog4/AvatarBlog4.png",

    },
    {
        id: 5,
        category: "Product",
        title:  "PM mental models",
        short: "Mental models are simple expressions of complex processes or relationships.",
        author_id: 5,
        author_name: "Demi WIlkinson",
        createdAt: '2025-01-16',
        preview: "/blogs/blog5/ImgBlog5.png",
        avatar: "blogs/blog5/AvatarBlog5.png",

    },
    {
        id: 6,
        category: "Design",
        title:  "What is Wireframing?",
        short: "Introduction to Wireframing and its Principles. Learn from the best in the industry.",
        author_id: 6,
        author_name: "Candice Wu",
        createdAt: '2025-01-15',
        preview: "/blogs/blog6/ImgBlog6.png",
        avatar: "blogs/blog6/AvatarBlog6.png",

    },
    {
        id: 7,
        category: "Design",
        title:  "How collaboration makes us better designers",
        short: "Collaboration can make our teams stronger, and our individual designs better.",
        author_id: 7,
        author_name: "Natali Craig",
        createdAt: '2025-01-14',
        preview: "/blogs/blog7/ImgBlog7.png",
        avatar: "blogs/blog7/AvatarBlog7.png",

    },
    {
        id: 8,
        category: "Product",
        title:  "Our top 10 Javascript frameworks to use",
        short: "JavaScript frameworks make development easy with extensive features and functionalities.",
        author_id: 8,
        author_name: "Drew Cano",
        createdAt: '2025-01-13',
        preview: "/blogs/blog8/ImgBlog8.png",
        avatar: "blogs/blog8/AvatarBlog8.png",

    },
    {
        id: 9,
        category: "Customer Success",
        title:  "Podcast: Creating a better CX Community",
        short: "Starting a community doesn’t need to be complicated, but how do you get started?",
        author_id: 9,
        author_name: "Orlando Diggs",
        createdAt: '2025-01-12',
        preview: "/blogs/blog9/ImgBlog9.png",
        avatar: "blogs/blog9/AvatarBlog9.png",

    },
]